	de2_115_WEB_Qsys u0 (
		.tri_state_bridge_flash_bridge_0_out_address_to_the_cfi_flash    (<connected-to-tri_state_bridge_flash_bridge_0_out_address_to_the_cfi_flash>),    // tri_state_bridge_flash_bridge_0_out.address_to_the_cfi_flash
		.tri_state_bridge_flash_bridge_0_out_tri_state_bridge_flash_data (<connected-to-tri_state_bridge_flash_bridge_0_out_tri_state_bridge_flash_data>), //                                    .tri_state_bridge_flash_data
		.tri_state_bridge_flash_bridge_0_out_write_n_to_the_cfi_flash    (<connected-to-tri_state_bridge_flash_bridge_0_out_write_n_to_the_cfi_flash>),    //                                    .write_n_to_the_cfi_flash
		.tri_state_bridge_flash_bridge_0_out_select_n_to_the_cfi_flash   (<connected-to-tri_state_bridge_flash_bridge_0_out_select_n_to_the_cfi_flash>),   //                                    .select_n_to_the_cfi_flash
		.tri_state_bridge_flash_bridge_0_out_read_n_to_the_cfi_flash     (<connected-to-tri_state_bridge_flash_bridge_0_out_read_n_to_the_cfi_flash>),     //                                    .read_n_to_the_cfi_flash
		.c0_out_clk_clk                                                  (<connected-to-c0_out_clk_clk>),                                                  //                          c0_out_clk.clk
		.c2_out_clk_clk                                                  (<connected-to-c2_out_clk_clk>),                                                  //                          c2_out_clk.clk
		.key_external_connection_export                                  (<connected-to-key_external_connection_export>),                                  //             key_external_connection.export
		.lcd_external_RS                                                 (<connected-to-lcd_external_RS>),                                                 //                        lcd_external.RS
		.lcd_external_RW                                                 (<connected-to-lcd_external_RW>),                                                 //                                    .RW
		.lcd_external_data                                               (<connected-to-lcd_external_data>),                                               //                                    .data
		.lcd_external_E                                                  (<connected-to-lcd_external_E>),                                                  //                                    .E
		.sd_clk_external_connection_export                               (<connected-to-sd_clk_external_connection_export>),                               //          sd_clk_external_connection.export
		.sd_cmd_external_connection_export                               (<connected-to-sd_cmd_external_connection_export>),                               //          sd_cmd_external_connection.export
		.sd_dat_external_connection_export                               (<connected-to-sd_dat_external_connection_export>),                               //          sd_dat_external_connection.export
		.sd_wp_n_external_connection_export                              (<connected-to-sd_wp_n_external_connection_export>),                              //         sd_wp_n_external_connection.export
		.epp_i2c_scl_external_connection_export                          (<connected-to-epp_i2c_scl_external_connection_export>),                          //     epp_i2c_scl_external_connection.export
		.epp_i2c_sda_external_connection_export                          (<connected-to-epp_i2c_sda_external_connection_export>),                          //     epp_i2c_sda_external_connection.export
		.seg7_conduit_end_export                                         (<connected-to-seg7_conduit_end_export>),                                         //                    seg7_conduit_end.export
		.sw_external_connection_export                                   (<connected-to-sw_external_connection_export>),                                   //              sw_external_connection.export
		.i2c_scl_external_connection_export                              (<connected-to-i2c_scl_external_connection_export>),                              //         i2c_scl_external_connection.export
		.i2c_sda_external_connection_export                              (<connected-to-i2c_sda_external_connection_export>),                              //         i2c_sda_external_connection.export
		.audio_conduit_end_XCK                                           (<connected-to-audio_conduit_end_XCK>),                                           //                   audio_conduit_end.XCK
		.audio_conduit_end_ADCDAT                                        (<connected-to-audio_conduit_end_ADCDAT>),                                        //                                    .ADCDAT
		.audio_conduit_end_ADCLRC                                        (<connected-to-audio_conduit_end_ADCLRC>),                                        //                                    .ADCLRC
		.audio_conduit_end_DACDAT                                        (<connected-to-audio_conduit_end_DACDAT>),                                        //                                    .DACDAT
		.audio_conduit_end_DACLRC                                        (<connected-to-audio_conduit_end_DACLRC>),                                        //                                    .DACLRC
		.audio_conduit_end_BCLK                                          (<connected-to-audio_conduit_end_BCLK>),                                          //                                    .BCLK
		.reset_reset_n                                                   (<connected-to-reset_reset_n>),                                                   //                               reset.reset_n
		.altpll_areset_conduit_export                                    (<connected-to-altpll_areset_conduit_export>),                                    //               altpll_areset_conduit.export
		.altpll_locked_conduit_export                                    (<connected-to-altpll_locked_conduit_export>),                                    //               altpll_locked_conduit.export
		.altpll_c1_clk                                                   (<connected-to-altpll_c1_clk>),                                                   //                           altpll_c1.clk
		.ir_external_connection_export                                   (<connected-to-ir_external_connection_export>),                                   //              ir_external_connection.export
		.rs232_external_connection_rxd                                   (<connected-to-rs232_external_connection_rxd>),                                   //           rs232_external_connection.rxd
		.rs232_external_connection_txd                                   (<connected-to-rs232_external_connection_txd>),                                   //                                    .txd
		.rs232_external_connection_cts_n                                 (<connected-to-rs232_external_connection_cts_n>),                                 //                                    .cts_n
		.rs232_external_connection_rts_n                                 (<connected-to-rs232_external_connection_rts_n>),                                 //                                    .rts_n
		.ledr_external_connection_export                                 (<connected-to-ledr_external_connection_export>),                                 //            ledr_external_connection.export
		.ledg_external_connection_export                                 (<connected-to-ledg_external_connection_export>),                                 //            ledg_external_connection.export
		.clk_50_clk_in_clk                                               (<connected-to-clk_50_clk_in_clk>),                                               //                       clk_50_clk_in.clk
		.sma_out_external_connection_export                              (<connected-to-sma_out_external_connection_export>),                              //         sma_out_external_connection.export
		.sma_in_external_connection_export                               (<connected-to-sma_in_external_connection_export>),                               //          sma_in_external_connection.export
		.sdram_wire_addr                                                 (<connected-to-sdram_wire_addr>),                                                 //                          sdram_wire.addr
		.sdram_wire_ba                                                   (<connected-to-sdram_wire_ba>),                                                   //                                    .ba
		.sdram_wire_cas_n                                                (<connected-to-sdram_wire_cas_n>),                                                //                                    .cas_n
		.sdram_wire_cke                                                  (<connected-to-sdram_wire_cke>),                                                  //                                    .cke
		.sdram_wire_cs_n                                                 (<connected-to-sdram_wire_cs_n>),                                                 //                                    .cs_n
		.sdram_wire_dq                                                   (<connected-to-sdram_wire_dq>),                                                   //                                    .dq
		.sdram_wire_dqm                                                  (<connected-to-sdram_wire_dqm>),                                                  //                                    .dqm
		.sdram_wire_ras_n                                                (<connected-to-sdram_wire_ras_n>),                                                //                                    .ras_n
		.sdram_wire_we_n                                                 (<connected-to-sdram_wire_we_n>),                                                 //                                    .we_n
		.sram_conduit_end_DQ                                             (<connected-to-sram_conduit_end_DQ>),                                             //                    sram_conduit_end.DQ
		.sram_conduit_end_ADDR                                           (<connected-to-sram_conduit_end_ADDR>),                                           //                                    .ADDR
		.sram_conduit_end_UB_n                                           (<connected-to-sram_conduit_end_UB_n>),                                           //                                    .UB_n
		.sram_conduit_end_LB_n                                           (<connected-to-sram_conduit_end_LB_n>),                                           //                                    .LB_n
		.sram_conduit_end_WE_n                                           (<connected-to-sram_conduit_end_WE_n>),                                           //                                    .WE_n
		.sram_conduit_end_CE_n                                           (<connected-to-sram_conduit_end_CE_n>),                                           //                                    .CE_n
		.sram_conduit_end_OE_n                                           (<connected-to-sram_conduit_end_OE_n>),                                           //                                    .OE_n
		.isp1362_if_0_conduit_end_DATA                                   (<connected-to-isp1362_if_0_conduit_end_DATA>),                                   //            isp1362_if_0_conduit_end.DATA
		.isp1362_if_0_conduit_end_ADDR                                   (<connected-to-isp1362_if_0_conduit_end_ADDR>),                                   //                                    .ADDR
		.isp1362_if_0_conduit_end_RD_N                                   (<connected-to-isp1362_if_0_conduit_end_RD_N>),                                   //                                    .RD_N
		.isp1362_if_0_conduit_end_WR_N                                   (<connected-to-isp1362_if_0_conduit_end_WR_N>),                                   //                                    .WR_N
		.isp1362_if_0_conduit_end_CS_N                                   (<connected-to-isp1362_if_0_conduit_end_CS_N>),                                   //                                    .CS_N
		.isp1362_if_0_conduit_end_RST_N                                  (<connected-to-isp1362_if_0_conduit_end_RST_N>),                                  //                                    .RST_N
		.isp1362_if_0_conduit_end_INT0                                   (<connected-to-isp1362_if_0_conduit_end_INT0>),                                   //                                    .INT0
		.isp1362_if_0_conduit_end_INT1                                   (<connected-to-isp1362_if_0_conduit_end_INT1>),                                   //                                    .INT1
		.altpll_c3_clk                                                   (<connected-to-altpll_c3_clk>),                                                   //                           altpll_c3.clk
		.tse_mac_pcs_mac_tx_clock_connection_clk                         (<connected-to-tse_mac_pcs_mac_tx_clock_connection_clk>),                         // tse_mac_pcs_mac_tx_clock_connection.clk
		.tse_mac_pcs_mac_rx_clock_connection_clk                         (<connected-to-tse_mac_pcs_mac_rx_clock_connection_clk>),                         // tse_mac_pcs_mac_rx_clock_connection.clk
		.tse_mac_mac_status_connection_set_10                            (<connected-to-tse_mac_mac_status_connection_set_10>),                            //       tse_mac_mac_status_connection.set_10
		.tse_mac_mac_status_connection_set_1000                          (<connected-to-tse_mac_mac_status_connection_set_1000>),                          //                                    .set_1000
		.tse_mac_mac_status_connection_eth_mode                          (<connected-to-tse_mac_mac_status_connection_eth_mode>),                          //                                    .eth_mode
		.tse_mac_mac_status_connection_ena_10                            (<connected-to-tse_mac_mac_status_connection_ena_10>),                            //                                    .ena_10
		.tse_mac_mac_rgmii_connection_rgmii_in                           (<connected-to-tse_mac_mac_rgmii_connection_rgmii_in>),                           //        tse_mac_mac_rgmii_connection.rgmii_in
		.tse_mac_mac_rgmii_connection_rgmii_out                          (<connected-to-tse_mac_mac_rgmii_connection_rgmii_out>),                          //                                    .rgmii_out
		.tse_mac_mac_rgmii_connection_rx_control                         (<connected-to-tse_mac_mac_rgmii_connection_rx_control>),                         //                                    .rx_control
		.tse_mac_mac_rgmii_connection_tx_control                         (<connected-to-tse_mac_mac_rgmii_connection_tx_control>),                         //                                    .tx_control
		.tse_mac_mac_mdio_connection_mdc                                 (<connected-to-tse_mac_mac_mdio_connection_mdc>),                                 //         tse_mac_mac_mdio_connection.mdc
		.tse_mac_mac_mdio_connection_mdio_in                             (<connected-to-tse_mac_mac_mdio_connection_mdio_in>),                             //                                    .mdio_in
		.tse_mac_mac_mdio_connection_mdio_out                            (<connected-to-tse_mac_mac_mdio_connection_mdio_out>),                            //                                    .mdio_out
		.tse_mac_mac_mdio_connection_mdio_oen                            (<connected-to-tse_mac_mac_mdio_connection_mdio_oen>)                             //                                    .mdio_oen
	);

